# Frontend Dockerfile
# Build and run a React application using Nginx
# Build stage
FROM node:20.14-bullseye-slim AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./ 

# Install dependencies
RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cache /usr/src/app/.npm && \
  npm install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Production stage
FROM nginx:stable-alpine-slim AS prod 

# copy the build artifacts from the build stage
COPY --from=build /app/dist/ /usr/share/nginx/html

# Copy the Nginx configuration file
COPY  nginx.conf /etc/nginx/conf.d/default.conf

# expose port 
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]