version: '3'

vars:
  REPO: tireni/demoapp-fe
  NAME: demoapp-fe
  TAG: v1.0.0
  PORT: 8080

tasks:
  build-image:
    desc: Build the Docker image
    cmds:
      - docker build -t {{.REPO}}:{{.TAG}} .

  run:
    desc: Run the Docker container
    cmds:
      # - docker run -d -p {{.PORT}}:{{.PORT}} --name {{.NAME}} {{.REPO}}:{{.TAG}}
      - |
        docker run -d \
          -p {{.PORT}}:{{.PORT}} \
          --name {{.NAME}} \
          --network demoapp-network \
          {{.REPO}}:{{.TAG}}

  push:
    desc: Push the Docker image to registry
    cmds:
      - docker push {{.REPO}}:{{.TAG}}

  stop:
    desc: Stop and remove the Docker container
    cmds:
      - docker stop {{.NAME}} || true
      - docker rm {{.NAME}} || true

  logs:
    desc: container logs
    cmds: 
      - docker logs {{.NAME}} 

  rebuild:
    desc: Stop, remove, rebuild, and run container
    deps: [stop]
    cmds:
      - task: build-image
      - task: run
