FROM python:3.12-slim AS generate-requirements
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN curl -sSL https://install.python-poetry.org | python3 - --version 1.8.2
COPY pyproject.toml poetry.lock ./
ENV PATH="/root/.local/bin:/opt/poetry/bin:$PATH"
RUN poetry export --output requirements.txt --without-hashes

###

FROM python:3.12-slim AS production
COPY --from=generate-requirements /requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . . 
CMD ["python", "main.py"]