version: "3"

vars:
  REPO: tireni/demoapp-loadgen
  TAG: v1.0.0
  NAME: demoapp-loadgen
  # API_URL: http://api-golang:8000


tasks:
  run:
    desc: Run the Docker container
    cmds:
      - |
        docker run -d \
          --name {{.NAME}} \
          -e API_URL="{{.API_URL}}" \
          --network demoapp-network \
          {{.REPO}}:{{.TAG}}

  push:
    desc: Push the Docker image to registry
    cmds:
      - docker push {{.REPO}}:{{.TAG}}

  stop:
    desc: Stop and remove the Docker container
    cmds:
      - docker stop {{.NAME}} || true
      - docker rm {{.NAME}} || true

  install:
    desc: Install load generator dependencies
    cmds:
      - poetry install --no-root

  run:
    desc: Start load generator
    cmds:
      # api-golang is listening on port 8000
      - API_URL=http://localhost:8000/ DELAY_MS=100 poetry run python main.py
