# Dockerfile for Node.js API
#buuid stage
FROM node:20.14-bullseye-slim AS build

# set environment variable for production
ENV NODE_ENV=production

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN --mount=type=cache,target=/usr/src/app/.npm \
  npm set cache /usr/src/app/.npm && \
  npm ci --only=production

# use a non-root user to run the application
USER node

# copy healthcheck script
COPY --chown=node:node ./healthcheck/ .

# copy sou
COPY --chown=node:node ./src /app

# expose 3000
EXPOSE 3000
CMD [ "node", "index.js" ]