version: '3'

vars:
  REPO: tireni/demoapp-nodeapi
  NAME: demoapp-nodeapi
  TAG: v1.0.0
  PORT: 3000
  # DATABASE_URL: 

tasks:
  build-image:
    desc: Build the Docker image
    cmds:
      - docker build -t {{.REPO}}:{{.TAG}} .

  run:
    desc: Run the Docker container
    cmds:
      - |
        docker run -d \
          -p {{.PORT}}:{{.PORT}} \
          --name {{.NAME}} \
          -e DATABASE_URL="{{.DATABASE_URL}}" \
          --network demoapp-network \
          {{.REPO}}:{{.TAG}}

  push:
    desc: Push the Docker image to registry
    cmds:
      - docker push {{.REPO}}:{{.TAG}}

  stop:
    desc: Stop and remove the Docker container
    cmds:
      - docker stop {{.NAME}} || true
      - docker rm {{.NAME}} || true

  logs:
    desc: container logs
    cmds: 
      - docker logs {{.NAME}} 

  rebuild:
    desc: Stop, remove, rebuild, and run container
    deps: [stop]
    cmds:
      - task: build-image
      - task: run
